export type FunnelTag = 'Lead Capture' | 'Booking' | 'Checkout' | 'Website'

export type Funnel = {
  file: string
  label: string
  tag: FunnelTag
  desc: string
  /** Public subfolder the HTML + thumbnail live under. Default 'funnels'. */
  dir?: 'funnels' | 'samples'
}

/**
 * Your funnel pages and website samples. Every entry is a PLACEHOLDER page
 * generated by scripts/make-placeholder-sites.mjs.
 *
 * To add your own: drop the page's HTML in public/funnels/ (single pages) or
 * public/samples/ (full websites), add an entry here, then run
 * `node scripts/make-thumbs.mjs` to render its thumbnails.
 */

const funnel = (n: string, tag: FunnelTag): Funnel => ({
  file: `placeholder-funnel-${n}.html`,
  label: `Workflow Interface Sample ${n}`,
  tag,
  desc: 'Illustrative operational web application interface designed for responsive desktop and mobile workflows.',
})

export const gymFunnel: Funnel[] = [
  funnel('01', 'Lead Capture'),
  funnel('02', 'Checkout'),
  funnel('03', 'Lead Capture'),
]

export const bookingFunnel: Funnel[] = [
  funnel('04', 'Booking'),
  funnel('05', 'Booking'),
  funnel('06', 'Booking'),
]

export const websiteFunnel: Funnel[] = [
  {
    file: 'placeholder-site-01.html',
    label: 'Dashboard Interface',
    tag: 'Website',
    desc: 'Illustrative interface pattern for desktop operational dashboards, key indicators, and activity logs.',
    dir: 'samples',
  },
  {
    file: 'placeholder-site-02.html',
    label: 'Responsive Application',
    tag: 'Website',
    desc: 'Illustrative interface pattern designed for desktop and mobile application workflows.',
    dir: 'samples',
  },
  {
    file: 'placeholder-site-03.html',
    label: 'Workflow Screen',
    tag: 'Website',
    desc: 'Illustrative step-by-step process interface for structured data capture and form validation.',
    dir: 'samples',
  },
  {
    file: 'placeholder-site-04.html',
    label: 'Data Entry Interface',
    tag: 'Website',
    desc: 'Illustrative high-density tabular and entry view for efficient field operator recording.',
    dir: 'samples',
  },
  {
    file: 'placeholder-site-05.html',
    label: 'Monitoring View',
    tag: 'Website',
    desc: 'Illustrative telemetry and equipment state visualization interface.',
    dir: 'samples',
  },
  {
    file: 'placeholder-site-06.html',
    label: 'Mobile Utility',
    tag: 'Website',
    desc: 'Illustrative compact, touch-optimized operational tool layout for handheld field devices.',
    dir: 'samples',
  },
]

/**
 * Tag -> color map. Brand-external colors that identify the page type, passed
 * to CSS via an inline --tag-color custom property.
 */
export const tagColors: Record<FunnelTag, string> = {
  'Lead Capture': '#8b5cf6',
  Booking: '#ec4899',
  Checkout: '#f59e0b',
  Website: '#FF7A1A',
}
